"""FX-54V: server-side HTML assembly for the "Market Context" page.

Presentation layer ONLY -- this module receives already-built,
JSON-safe view-model dicts (see `apps.api.view_models.*`) and a handful
of already-resolved query-param strings; it never touches a
repository, never imports SQLAlchemy, and performs no PIT logic of its
own. Matches this project's existing "no framework" precedent
(`fta_dashboard_sketch.html`'s own inline-CSS/vanilla-JS/SVG-canvas
style, generated by `scripts/export_backtest_report.py`) rather than
introducing Jinja2/a template engine or any JS framework/build chain --
neither exists anywhere else in this codebase (see `docs/DECISIONS.md`'s
FX-54V entry for the inspection that confirmed this).

All chart-drawing JavaScript below is vanilla, inline, and reads ONLY
from a single embedded `window.__MARKET_CONTEXT__` JSON payload built
server-side by the SAME view-model builders the JSON API routes use --
there is no client-side fetch, no external CDN, and no possibility of
the page silently drifting from the API's own contract.
"""

import json
from html import escape

from forex_agent.apps.api.pairs import SUPPORTED_PAIRS

_PAGE_TITLE = "Market Context"


def render_market_context_page(
    *,
    selected_pair: str,
    as_of_param: str | None,
    rate_semantics_param: str,
    lookahead_hours: float,
    lookback_hours: float,
    fx46_experiment: str,
    fundamentals_view: dict[str, object],
    history_view: dict[str, object],
    events_view: dict[str, object],
    fx46_view: dict[str, object],
) -> str:
    resolved_as_of = str(events_view["as_of"])
    payload = {
        "fundamentals": fundamentals_view,
        "history": history_view,
        "events": events_view,
        "fx46": fx46_view,
    }
    payload_json = json.dumps(payload).replace(
        "</", "<\\/"
    )  # never let a literal </script> escape early

    pair_options = "".join(
        f'<option value="{escape(code)}"{" selected" if code == selected_pair else ""}>{escape(code)}</option>'
        for code in sorted(SUPPORTED_PAIRS)
    )
    semantics_options = "".join(
        f'<option value="{value}"{" selected" if value == rate_semantics_param else ""}>{value}</option>'
        for value in ("ANNOUNCED", "EFFECTIVE")
    )
    experiment_options = "".join(
        f'<option value="{value}"{" selected" if value == fx46_experiment else ""}>{value}</option>'
        for value in ("LEVEL", "CHANGE")
    )

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{_PAGE_TITLE}</title>
{_STYLE}
</head>
<body>
<header class="mc-header">
  <h1>Market Context</h1>
  <form method="get" action="/market-context" class="mc-controls" aria-label="Market context controls">
    <label>Pair
      <select name="pair">{pair_options}</select>
    </label>
    <label>As of (UTC, ISO 8601)
      <input type="text" name="as_of" value="{escape(as_of_param or resolved_as_of)}" size="26">
    </label>
    <label>Rate semantics
      <select name="rate_semantics">{semantics_options}</select>
    </label>
    <label>Lookahead (hours)
      <input type="number" name="lookahead_hours" value="{lookahead_hours:g}" min="0" step="1">
    </label>
    <label>Lookback (hours)
      <input type="number" name="lookback_hours" value="{lookback_hours:g}" min="0" step="1">
    </label>
    <label>FX-46 experiment
      <select name="fx46_experiment">{experiment_options}</select>
    </label>
    <button type="submit">Apply</button>
  </form>
  <p class="mc-as-of-banner">Showing evidence knowable as of <strong>{escape(resolved_as_of)}</strong> (UTC).
  Absence of evidence below is not evidence of safety -- see Coverage.</p>
</header>

<section id="fundamentals" aria-labelledby="fundamentals-heading">
  <h2 id="fundamentals-heading">Fundamentals</h2>
  <div class="panel" id="fundamentals-card"></div>
  <div class="mc-grid-2">
    <div class="panel">
      <h3>Policy-rate history</h3>
      <svg id="rate-history-chart" viewBox="0 0 640 220" role="img" aria-labelledby="rate-history-title">
        <title id="rate-history-title">Policy-rate history chart</title>
      </svg>
      <table class="mc-fallback-table" id="rate-history-table"></table>
    </div>
    <div class="panel">
      <h3>Rate expectations</h3>
      <p class="mc-status-row">Rate expectations: <strong>Deferred</strong> -- licensed historical futures
      data pending (FX-49). This is a project-capability status, not market evidence.</p>
    </div>
  </div>
  <div class="panel">
    <h3>FX-46 research evidence</h3>
    <p class="mc-research-note" id="fx46-conclusion"></p>
    <svg id="fx46-chart" viewBox="0 0 640 220" role="img" aria-labelledby="fx46-title">
      <title id="fx46-title">FX-46 confidence-interval plot</title>
    </svg>
    <table class="mc-fallback-table" id="fx46-table"></table>
  </div>
</section>

<section id="economic-events" aria-labelledby="events-heading">
  <h2 id="events-heading">Economic Events</h2>
  <div class="panel">
    <svg id="event-timeline" viewBox="0 0 640 120" role="img" aria-labelledby="timeline-title">
      <title id="timeline-title">Economic event timeline around now</title>
    </svg>
  </div>
  <div class="mc-grid-2">
    <div class="panel">
      <h3>Upcoming</h3>
      <div id="upcoming-cards"></div>
    </div>
    <div class="panel">
      <h3>Recent releases</h3>
      <div id="recent-cards"></div>
    </div>
  </div>
  <div class="panel">
    <h3>Coverage / limitations</h3>
    <div id="coverage-content"></div>
  </div>
</section>

<script>window.__MARKET_CONTEXT__ = {payload_json};</script>
{_SCRIPT}
</body>
</html>
"""


_STYLE = """<style>
:root {
  --mc-bg: #f6f7f9;
  --mc-panel-bg: #ffffff;
  --mc-text: #1a1d21;
  --mc-muted: #5b6470;
  --mc-border: #d7dbe0;
  --mc-accent: #2f6fed;
  --mc-status-cancelled: #8a8f98;
  --mc-status-postponed: #b98900;
  --mc-status-unavailable: #8a8f98;
}
@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) {
    --mc-bg: #0f1216;
    --mc-panel-bg: #171b20;
    --mc-text: #e7eaee;
    --mc-muted: #9aa3ad;
    --mc-border: #2b3138;
    --mc-accent: #6ea2ff;
    --mc-status-cancelled: #9aa3ad;
    --mc-status-postponed: #e0b23c;
    --mc-status-unavailable: #9aa3ad;
  }
}
body { background: var(--mc-bg); color: var(--mc-text); font-family: -apple-system, "Segoe UI", Roboto, sans-serif; margin: 0; padding: 0 0 3rem; }
.mc-header { padding: 1rem 1.5rem; border-bottom: 1px solid var(--mc-border); }
.mc-header h1 { margin: 0 0 0.75rem; font-size: 1.4rem; }
.mc-controls { display: flex; flex-wrap: wrap; gap: 0.75rem; align-items: end; }
.mc-controls label { display: flex; flex-direction: column; font-size: 0.75rem; color: var(--mc-muted); gap: 0.25rem; }
.mc-controls select, .mc-controls input, .mc-controls button { font-size: 0.9rem; padding: 0.3rem 0.4rem; }
.mc-as-of-banner { margin: 0.75rem 0 0; font-size: 0.85rem; color: var(--mc-muted); }
section { padding: 1rem 1.5rem; }
section h2 { font-size: 1.1rem; border-bottom: 1px solid var(--mc-border); padding-bottom: 0.4rem; }
.panel { background: var(--mc-panel-bg); border: 1px solid var(--mc-border); border-radius: 6px; padding: 0.9rem; margin-bottom: 1rem; }
.mc-grid-2 { display: grid; grid-template-columns: 1fr 1fr; gap: 1rem; }
@media (max-width: 860px) { .mc-grid-2 { grid-template-columns: 1fr; } }
.mc-fallback-table { width: 100%; border-collapse: collapse; font-size: 0.8rem; margin-top: 0.5rem; }
.mc-fallback-table caption { text-align: left; color: var(--mc-muted); font-size: 0.75rem; margin-bottom: 0.25rem; }
.mc-fallback-table th, .mc-fallback-table td { border-bottom: 1px solid var(--mc-border); padding: 0.25rem 0.4rem; text-align: left; }
.mc-research-note { font-size: 0.9rem; font-style: italic; color: var(--mc-muted); border-left: 3px solid var(--mc-accent); padding-left: 0.6rem; }
.mc-status-row { font-size: 0.9rem; color: var(--mc-muted); }
.mc-card { border: 1px solid var(--mc-border); border-radius: 5px; padding: 0.6rem 0.8rem; margin-bottom: 0.6rem; font-size: 0.85rem; }
.mc-card .mc-card-title { font-weight: 600; margin-bottom: 0.2rem; }
.mc-card .mc-card-meta { color: var(--mc-muted); font-size: 0.78rem; }
.mc-badge { display: inline-block; border-radius: 3px; padding: 0.05rem 0.4rem; font-size: 0.72rem; font-weight: 600; border: 1px solid var(--mc-border); }
.mc-badge-cancelled { color: var(--mc-status-cancelled); border-color: var(--mc-status-cancelled); }
.mc-badge-postponed { color: var(--mc-status-postponed); border-color: var(--mc-status-postponed); }
.mc-badge-unavailable { color: var(--mc-status-unavailable); border-color: var(--mc-status-unavailable); }
.mc-fund-grid { display: grid; grid-template-columns: 1fr auto 1fr; gap: 1rem; align-items: center; text-align: center; }
.mc-fund-rate { font-size: 1.6rem; font-weight: 700; }
.mc-fund-label { font-size: 0.78rem; color: var(--mc-muted); text-transform: uppercase; letter-spacing: 0.03em; }
.mc-fund-diff { font-size: 1.1rem; }
.mc-empty-message { color: var(--mc-muted); font-style: italic; }
.mc-coverage-item { margin-bottom: 0.3rem; font-size: 0.85rem; }
.mc-sr-only { position: absolute; left: -9999px; }
</style>"""

_SCRIPT = """<script>
(function () {
  const DATA = window.__MARKET_CONTEXT__;
  const NS = "http://www.w3.org/2000/svg";

  function el(tag, attrs, text) {
    const e = document.createElementNS(NS, tag);
    for (const k in attrs) e.setAttribute(k, attrs[k]);
    if (text !== undefined) e.textContent = text;
    return e;
  }
  function htmlEl(tag, attrs, text) {
    const e = document.createElement(tag);
    for (const k in (attrs || {})) e.setAttribute(k, attrs[k]);
    if (text !== undefined) e.textContent = text;
    return e;
  }

  // --- Fundamentals card -----------------------------------------------
  function renderFundamentals() {
    const f = DATA.fundamentals;
    const card = document.getElementById("fundamentals-card");
    const grid = htmlEl("div", { class: "mc-fund-grid" });

    function sideBlock(side, currency) {
      const wrap = htmlEl("div");
      wrap.appendChild(htmlEl("div", { class: "mc-fund-label" }, currency + " policy rate"));
      if (side.available) {
        wrap.appendChild(htmlEl("div", { class: "mc-fund-rate" }, side.rate_percent + "%"));
        wrap.appendChild(htmlEl("div", { class: "mc-card-meta" },
          f.rate_semantics + " · observed " + side.observation_period));
        if (!side.released_at_is_verified && !side.released_at_is_conservative_bound) {
          wrap.appendChild(htmlEl("div", { class: "mc-card-meta" }, "timing: provisional"));
        }
      } else {
        wrap.appendChild(htmlEl("div", { class: "mc-fund-rate mc-empty-message" }, "Data unavailable"));
        wrap.appendChild(htmlEl("div", { class: "mc-card-meta" }, side.unavailable_reason || ""));
      }
      return wrap;
    }

    grid.appendChild(sideBlock(f.base, f.base_currency));

    const diffWrap = htmlEl("div");
    diffWrap.appendChild(htmlEl("div", { class: "mc-fund-label" }, f.differential.label));
    if (f.differential.available) {
      diffWrap.appendChild(htmlEl("div", { class: "mc-fund-diff" }, f.differential.value_pp + " pp"));
    } else {
      diffWrap.appendChild(htmlEl("div", { class: "mc-fund-diff mc-empty-message" }, "Data unavailable"));
    }
    grid.appendChild(diffWrap);

    grid.appendChild(sideBlock(f.quote, f.quote_currency));
    card.innerHTML = "";
    card.appendChild(grid);
  }

  // --- Policy-rate history chart -----------------------------------------
  function renderRateHistory() {
    const h = DATA.history;
    const svg = document.getElementById("rate-history-chart");
    const table = document.getElementById("rate-history-table");
    svg.innerHTML = '<title id="rate-history-title">Policy-rate history chart</title>';
    table.innerHTML = "";

    const series = [
      { label: h.base_currency, points: h.base_history, color: "#2f6fed" },
      { label: h.quote_currency, points: h.quote_history, color: "#e07a29" },
    ];
    const allPoints = series.flatMap(s => s.points);
    if (allPoints.length === 0) {
      svg.appendChild(el("text", { x: 20, y: 110, fill: "var(--mc-muted)" }, "No stored history for either currency."));
      return;
    }

    const W = 640, H = 220, padL = 46, padR = 12, padT = 14, padB = 26;
    const dateOf = p => new Date(h.rate_semantics === "ANNOUNCED" ? p.released_at : (p.effective_at || p.released_at));
    const xs = allPoints.map(dateOf).map(d => d.getTime());
    const ys = allPoints.map(p => parseFloat(p.rate_percent));
    const xMin = Math.min(...xs), xMax = Math.max(...xs);
    const yMin = Math.min(0, ...ys), yMax = Math.max(...ys) + 0.5;
    const x = t => padL + (xMax === xMin ? 0 : (t - xMin) / (xMax - xMin)) * (W - padL - padR);
    const y = v => (H - padB) - ((v - yMin) / (yMax - yMin || 1)) * (H - padT - padB);

    svg.appendChild(el("line", { x1: padL, y1: y(0), x2: W - padR, y2: y(0), stroke: "var(--mc-border)" }));

    const captionParts = [];
    series.forEach(s => {
      if (s.points.length === 0) {
        captionParts.push(s.label + ": no history");
        return;
      }
      let d = "";
      s.points.forEach((p, i) => {
        const px = x(dateOf(p).getTime()), py = y(parseFloat(p.rate_percent));
        d += (i === 0 ? "M" : "L") + px.toFixed(1) + "," + py.toFixed(1);
        if (i < s.points.length - 1) {
          const nx = x(dateOf(s.points[i + 1]).getTime());
          d += "L" + nx.toFixed(1) + "," + py.toFixed(1); // step, never interpolated
        }
      });
      svg.appendChild(el("path", { d, fill: "none", stroke: s.color, "stroke-width": "2" }));
      captionParts.push(s.label + ": " + s.points.length + " known decision(s)");
    });
    svg.appendChild(el("text", { x: padL, y: 12, fill: "var(--mc-muted)", "font-size": "10" },
      h.rate_semantics + " semantics · " + captionParts.join(" · ")));

    const caption = htmlEl("caption", {}, "Policy-rate history (" + h.rate_semantics + "): " + captionParts.join("; "));
    table.appendChild(caption);
    const thead = htmlEl("tr");
    ["Currency", "Observation period", "Rate (%)", "Released at", "Effective at"].forEach(t => thead.appendChild(htmlEl("th", {}, t)));
    table.appendChild(thead);
    series.forEach(s => s.points.forEach(p => {
      const row = htmlEl("tr");
      [s.label, p.observation_period, p.rate_percent, p.released_at, p.effective_at || "Not established"].forEach(v => row.appendChild(htmlEl("td", {}, String(v))));
      table.appendChild(row);
    }));
  }

  // --- FX-46 forest / CI plot --------------------------------------------
  function renderFx46() {
    const fx = DATA.fx46;
    document.getElementById("fx46-conclusion").textContent = "Research result: " + fx.research_conclusion_note;
    const svg = document.getElementById("fx46-chart");
    const table = document.getElementById("fx46-table");
    svg.innerHTML = '<title id="fx46-title">FX-46 confidence-interval plot</title>';
    table.innerHTML = "";

    if (!fx.result) {
      svg.appendChild(el("text", { x: 20, y: 110, fill: "var(--mc-muted)" },
        "No FX-46 result for " + fx.selected_pair + " / " + fx.selected_rate_semantics + " / " + fx.selected_experiment + "."));
      return;
    }
    const horizons = Object.keys(fx.result.primary_contrast.by_horizon).sort((a, b) => parseInt(a) - parseInt(b));
    const W = 640, H = 220, padL = 60, padR = 20, padT = 20, padB = 30;
    const rowH = (H - padT - padB) / horizons.length;

    const bounds = [];
    horizons.forEach(hz => {
      const c = fx.result.primary_contrast.by_horizon[hz];
      if (c.lower_95 !== null) bounds.push(parseFloat(c.lower_95), parseFloat(c.upper_95));
    });
    const maxAbs = bounds.length ? Math.max(0.0005, ...bounds.map(Math.abs)) : 0.001;
    const x = v => padL + ((v + maxAbs) / (2 * maxAbs)) * (W - padL - padR);

    svg.appendChild(el("line", { x1: x(0), y1: padT, x2: x(0), y2: H - padB, stroke: "var(--mc-muted)", "stroke-dasharray": "3,3" }));
    svg.appendChild(el("text", { x: x(0) - 10, y: H - padB + 14, fill: "var(--mc-muted)", "font-size": "10" }, "0"));

    const captionParts = [];
    horizons.forEach((hz, i) => {
      const c = fx.result.primary_contrast.by_horizon[hz];
      const cy = padT + rowH * (i + 0.5);
      svg.appendChild(el("text", { x: 4, y: cy + 4, fill: "var(--mc-text)", "font-size": "11" }, hz + "d"));
      if (c.lower_95 === null) {
        svg.appendChild(el("text", { x: padL, y: cy + 4, fill: "var(--mc-muted)", "font-size": "10" }, "not computable"));
        captionParts.push(hz + "d: not computable");
        return;
      }
      const lo = x(parseFloat(c.lower_95)), hi = x(parseFloat(c.upper_95)), pt = x(parseFloat(c.observed_diff));
      svg.appendChild(el("line", { x1: lo, y1: cy, x2: hi, y2: cy, stroke: "var(--mc-accent)", "stroke-width": "2" }));
      svg.appendChild(el("circle", { cx: pt, cy: cy, r: 4, fill: "var(--mc-accent)" }));
      captionParts.push(hz + "d: " + c.observed_diff + " [" + c.lower_95 + ", " + c.upper_95 + "]" + (c.crosses_zero ? " (crosses zero)" : ""));
    });
    svg.appendChild(el("text", { x: padL, y: 12, fill: "var(--mc-muted)", "font-size": "10" },
      fx.selected_pair + " · " + fx.selected_rate_semantics + " · " + fx.selected_experiment +
      " · " + fx.result.primary_contrast.group_a + " vs " + fx.result.primary_contrast.group_b));

    const caption = htmlEl("caption", {}, "Confidence intervals by horizon: " + captionParts.join("; "));
    table.appendChild(caption);
    const thead = htmlEl("tr");
    ["Horizon", "Observed diff", "95% CI low", "95% CI high", "Crosses zero", "n (A/B)", "Note"].forEach(t => thead.appendChild(htmlEl("th", {}, t)));
    table.appendChild(thead);
    horizons.forEach(hz => {
      const c = fx.result.primary_contrast.by_horizon[hz];
      const row = htmlEl("tr");
      [hz + "d", c.observed_diff ?? "—", c.lower_95 ?? "—", c.upper_95 ?? "—",
       c.crosses_zero === null ? "—" : (c.crosses_zero ? "yes" : "no"),
       c.n_a + " / " + c.n_b, c.note || ""].forEach(v => row.appendChild(htmlEl("td", {}, String(v))));
      table.appendChild(row);
    });
    const dc = fx.result.disposition_counts;
    table.appendChild(htmlEl("caption", {}, "Sample coverage: " + dc.total + " rows total, by disposition: " + JSON.stringify(dc.by_disposition)));
  }

  // --- Event timeline -----------------------------------------------------
  function renderTimeline() {
    const ev = DATA.events;
    const svg = document.getElementById("event-timeline");
    svg.innerHTML = '<title id="timeline-title">Economic event timeline around now</title>';
    const W = 640, H = 120, mid = W / 2;
    svg.appendChild(el("line", { x1: 20, y1: 60, x2: W - 20, y2: 60, stroke: "var(--mc-border)" }));
    svg.appendChild(el("line", { x1: mid, y1: 20, x2: mid, y2: 100, stroke: "var(--mc-accent)", "stroke-width": "2" }));
    svg.appendChild(el("text", { x: mid, y: 14, "text-anchor": "middle", fill: "var(--mc-accent)", "font-size": "11" }, "NOW"));

    const asOf = new Date(ev.as_of).getTime();
    const lookaheadMs = ev.lookahead_seconds * 1000, lookbackMs = ev.lookback_seconds * 1000;

    function placeExact(items, isFuture) {
      items.forEach(it => {
        if (it.exactTime === null) return;
        const dt = new Date(it.exactTime).getTime();
        const span = isFuture ? lookaheadMs : lookbackMs;
        const frac = span === 0 ? 0 : Math.min(1, Math.abs(dt - asOf) / span);
        const px = isFuture ? mid + frac * (W / 2 - 30) : mid - frac * (W / 2 - 30);
        svg.appendChild(el("circle", { cx: px, cy: 60, r: 5, fill: isFuture ? "#2f6fed" : "#e07a29" }));
        svg.appendChild(el("title", {}, it.label));
      });
    }

    const upcomingExact = [];
    ev.upcoming_schedule_groups.forEach(g => g.members.forEach(m => {
      if (m.exact_scheduled_at_utc) upcomingExact.push({ exactTime: m.exact_scheduled_at_utc, label: m.display_name });
    }));
    const recentExact = [];
    ev.recent_release_groups.forEach(g => g.members.forEach(m => {
      if (m.exact_released_at_utc) recentExact.push({ exactTime: m.exact_released_at_utc, label: m.display_name });
    }));
    placeExact(upcomingExact, true);
    placeExact(recentExact, false);

    const dateOnlyCount =
      ev.upcoming_schedule_groups.flatMap(g => g.members).filter(m => m.exact_scheduled_at_utc === null).length +
      ev.recent_release_groups.flatMap(g => g.members).filter(m => m.exact_released_at_utc === null).length;
    if (dateOnlyCount > 0) {
      svg.appendChild(el("text", { x: 20, y: 112, fill: "var(--mc-muted)", "font-size": "10" },
        dateOnlyCount + " date-only/TBD event(s) shown only in the cards below, never placed on this instant timeline."));
    }
  }

  // --- Upcoming / recent cards ---------------------------------------------
  function statusBadge(status) {
    if (status === "CANCELLED") return htmlEl("span", { class: "mc-badge mc-badge-cancelled" }, "CANCELLED");
    if (status === "POSTPONED") return htmlEl("span", { class: "mc-badge mc-badge-postponed" }, "POSTPONED");
    return null;
  }

  function renderScheduleCard(member) {
    const card = htmlEl("div", { class: "mc-card" });
    const title = htmlEl("div", { class: "mc-card-title" });
    title.appendChild(document.createTextNode(member.display_name + " (" + member.currency + ", " + member.pair_role + ") "));
    const badge = statusBadge(member.status);
    if (badge) title.appendChild(badge);
    card.appendChild(title);
    const timeText = member.scheduled_time === null ? "Time TBD" : member.scheduled_time + " " + member.schedule_timezone;
    let line = member.scheduled_date + " · " + timeText;
    if (member.exact_scheduled_at_utc) line += " · UTC " + member.exact_scheduled_at_utc;
    if (member.time_until_event_seconds !== null) {
      const hrs = (member.time_until_event_seconds / 3600).toFixed(1);
      line += " · in " + hrs + "h";
    }
    card.appendChild(htmlEl("div", { class: "mc-card-meta" }, line));
    card.appendChild(htmlEl("div", { class: "mc-card-meta" },
      "Availability confidence: " + member.availability_confidence + " · Source: " + member.source));
    return card;
  }

  function renderReleaseCard(member) {
    const card = htmlEl("div", { class: "mc-card" });
    card.appendChild(htmlEl("div", { class: "mc-card-title" },
      member.display_name + " (" + member.currency + ", " + member.pair_role + ")"));
    const timeText = member.released_time === null ? "Time TBD" : member.released_time + " " + member.released_timezone;
    let line = "Released " + member.released_date + " · " + timeText;
    if (member.exact_released_at_utc) line += " · UTC " + member.exact_released_at_utc;
    if (member.elapsed_since_release_seconds !== null) {
      const hrs = (member.elapsed_since_release_seconds / 3600).toFixed(1);
      line += " · " + hrs + "h ago";
    }
    card.appendChild(htmlEl("div", { class: "mc-card-meta" }, line));
    const provLine = "Source published: " + (member.source_published_at || "unknown") +
      " · Availability: " + (member.availability || "unknown") + " · Source: " + member.source;
    card.appendChild(htmlEl("div", { class: "mc-card-meta" }, provLine));
    return card;
  }

  function renderGroupsInto(containerId, groups, memberRenderer, emptyMessage) {
    const container = document.getElementById(containerId);
    container.innerHTML = "";
    if (groups.length === 0) {
      container.appendChild(htmlEl("p", { class: "mc-empty-message" }, emptyMessage));
      return;
    }
    groups.forEach(g => {
      if (g.is_package) {
        const wrap = htmlEl("div", { class: "mc-card" });
        wrap.appendChild(htmlEl("div", { class: "mc-card-title" }, "Release package (" + g.members.length + " members)"));
        g.members.forEach(m => wrap.appendChild(memberRenderer(m)));
        container.appendChild(wrap);
      } else {
        container.appendChild(memberRenderer(g.members[0]));
      }
    });
  }

  function renderCards() {
    const ev = DATA.events;
    renderGroupsInto("upcoming-cards", ev.upcoming_schedule_groups, renderScheduleCard,
      ev.empty_schedule_window_message || "No tracked PIT-visible events in this window.");
    renderGroupsInto("recent-cards", ev.recent_release_groups, renderReleaseCard,
      ev.empty_release_window_message || "No tracked PIT-visible release evidence in this window.");
  }

  // --- Coverage panel -------------------------------------------------------
  function renderCoverage() {
    const ev = DATA.events;
    const container = document.getElementById("coverage-content");
    container.innerHTML = "";
    ev.coverage.tracked_indicator_keys_by_currency.forEach(entry => {
      const line = entry.indicator_keys.length > 0
        ? entry.currency + ": " + entry.indicator_keys.length + " tracked indicator(s) -- " + entry.indicator_keys.join(", ")
        : entry.currency + ": no tracked official-calendar indicators";
      container.appendChild(htmlEl("div", { class: "mc-coverage-item" }, line));
    });
    if (ev.coverage.untracked_pair_currencies.length > 0) {
      container.appendChild(htmlEl("div", { class: "mc-coverage-item" },
        "Untracked currencies for this pair: " + ev.coverage.untracked_pair_currencies.join(", ")));
    }
    container.appendChild(htmlEl("div", { class: "mc-coverage-item mc-empty-message" },
      "\\"Tracked\\" does not mean complete coverage, and does not mean the live source is currently healthy. " +
      ev.coverage.source_health_note));
  }

  renderFundamentals();
  renderRateHistory();
  renderFx46();
  renderTimeline();
  renderCards();
  renderCoverage();
})();
</script>"""
