"""add ingestion watermarks

FX-26: one row per (instrument, granularity), tracking the contiguous
`[earliest_ingested, latest_ingested)` interval durably backfilled from
the provider so far — the resumability mechanism `BackfillCandles` reads
and writes. See `domain.candle_pagination`/`application.use_cases.
backfill_candles`.

Revision ID: 3a043ed9c1ed
Revises: 635084cc3eb0
Create Date: 2026-09-19 14:47:40.762393

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "3a043ed9c1ed"
down_revision: str | None = "635084cc3eb0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ingestion_watermarks",
        sa.Column("instrument", sa.String(), nullable=False),
        sa.Column("granularity", sa.String(), nullable=False),
        sa.Column("earliest_ingested", sa.DateTime(timezone=True), nullable=False),
        sa.Column("latest_ingested", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "instrument", "granularity", name="uq_ingestion_watermarks_instrument_granularity"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ingestion_watermarks")
    # ### end Alembic commands ###
