"""add released_at_is_verified to macro observation vintages

FX-43H: marks whether a vintage's released_at/effective_at are confirmed
timestamps (True, the default -- unaffected for every existing row and
every existing caller) or a provisional proxy (False -- e.g. FX-43's
policy-rate backfill, which used an effective-date proxy for
released_at). See domain.macro_observation_vintage and
application.ports.macro_observation_repository.
replace_provisional_release_timing.

Revision ID: 5707ecb39242
Revises: 7f04ea660a34
Create Date: 2026-09-21 23:56:58.300011

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "5707ecb39242"
down_revision: str | None = "7f04ea660a34"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "macro_observation_vintages",
        sa.Column("released_at_is_verified", sa.Boolean(), server_default="true", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("macro_observation_vintages", "released_at_is_verified")
    # ### end Alembic commands ###
