"""add candle source provenance

FX-24: a `source` column (`NATIVE`/`AGGREGATED`, see
`domain.candle_source.CandleSource`) is added to the unique constraint,
not just stored — a native candle and a self-aggregated candle for the
same instrument/granularity/start_time can now coexist in storage
without colliding or silently overwriting each other in an upsert.

No backfill needed: this table has no production data yet (nothing
calls `IngestCandles`/`AggregateCandles` on a schedule or via a trigger
as of FX-24 — see docs/CURRENT_STATE.md), so the column can be added
`NOT NULL` directly rather than needing a default-then-backfill dance.

Revision ID: 635084cc3eb0
Revises: 91c1293c5760
Create Date: 2026-09-15 02:48:51.824354

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "635084cc3eb0"
down_revision: str | None = "91c1293c5760"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("candles", sa.Column("source", sa.String(), nullable=False))
    op.drop_constraint(
        op.f("uq_candles_instrument_granularity_start_time"), "candles", type_="unique"
    )
    op.create_unique_constraint(
        "uq_candles_instrument_granularity_start_time_source",
        "candles",
        ["instrument", "granularity", "start_time", "source"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_candles_instrument_granularity_start_time_source", "candles", type_="unique"
    )
    op.create_unique_constraint(
        op.f("uq_candles_instrument_granularity_start_time"),
        "candles",
        ["instrument", "granularity", "start_time"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("candles", "source")
    # ### end Alembic commands ###
