"""add macro observation vintages

FX-41: point-in-time-safe storage for macro/fundamental observations. Each
row is one immutable vintage — a first release or a later revision of one
(series_key, observation_period) pair. No application code path ever
UPDATEs `value`, `released_at`, or `revision_sequence` on an existing row;
a revision is always a new row. See `domain.macro_observation_vintage`/
`application.ports.macro_observation_repository`.

Revision ID: 7f04ea660a34
Revises: 3a043ed9c1ed
Create Date: 2026-09-21 10:56:12.609795

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "7f04ea660a34"
down_revision: str | None = "3a043ed9c1ed"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "macro_observation_vintages",
        sa.Column("series_key", sa.String(), nullable=False),
        sa.Column("observation_period", sa.DateTime(timezone=True), nullable=False),
        sa.Column("value", sa.Numeric(), nullable=False),
        sa.Column("released_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("effective_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revision_sequence", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "series_key",
            "observation_period",
            "revision_sequence",
            name="uq_macro_observation_vintages_series_period_revision",
        ),
    )
    op.create_index(
        "ix_macro_observation_vintages_series_key_released_at",
        "macro_observation_vintages",
        ["series_key", "released_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_macro_observation_vintages_series_key_released_at",
        table_name="macro_observation_vintages",
    )
    op.drop_table("macro_observation_vintages")
    # ### end Alembic commands ###
