"""create candles table

FX-5: storage for historical candles (FX-6 will populate it from OANDA).
Unique constraint on (instrument, granularity, start_time) is what makes
repeated ingestion idempotent via upsert — see
forex_agent.infrastructure.db.candle_repository.

Revision ID: 91c1293c5760
Revises: 06755c32d64c
Create Date: 2026-09-13 01:22:34.831838

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "91c1293c5760"
down_revision: str | None = "06755c32d64c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "candles",
        sa.Column("instrument", sa.String(), nullable=False),
        sa.Column("granularity", sa.String(), nullable=False),
        sa.Column("start_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("bid_open", sa.Numeric(), nullable=False),
        sa.Column("bid_high", sa.Numeric(), nullable=False),
        sa.Column("bid_low", sa.Numeric(), nullable=False),
        sa.Column("bid_close", sa.Numeric(), nullable=False),
        sa.Column("ask_open", sa.Numeric(), nullable=False),
        sa.Column("ask_high", sa.Numeric(), nullable=False),
        sa.Column("ask_low", sa.Numeric(), nullable=False),
        sa.Column("ask_close", sa.Numeric(), nullable=False),
        sa.Column("volume", sa.Integer(), nullable=False),
        sa.Column("is_finalized", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "instrument",
            "granularity",
            "start_time",
            name="uq_candles_instrument_granularity_start_time",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("candles")
    # ### end Alembic commands ###
