"""add economic event tables

FX-51: canonical, provider-neutral, point-in-time-safe persistence for
scheduled economic events. `economic_event_occurrences` holds one row
per (indicator_key, reference_period) -- an occurrence's stable
identity, never a scheduled timestamp. The three vintage tables
(schedule/consensus/actual-value) each hold one immutable row per
revision, referencing their occurrence via a genuine composite FOREIGN
KEY into `economic_event_occurrences`' own unique constraint -- no
application code path ever UPDATEs an existing vintage row; a
reschedule/consensus revision/value revision is always a new row. See
`domain.economic_event_occurrence`/`domain.economic_event_schedule_
vintage`/`domain.economic_event_consensus_vintage`/`domain.economic_
event_actual_value_vintage`/`application.ports.economic_event_
repository`.

Revision ID: bb7551fcef3a
Revises: f350d505412b
Create Date: 2026-09-26 01:18:19.432910

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "bb7551fcef3a"
down_revision: str | None = "f350d505412b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "economic_event_occurrences",
        sa.Column("indicator_key", sa.String(), nullable=False),
        sa.Column("reference_period", sa.DateTime(timezone=True), nullable=False),
        sa.Column("release_group_key", sa.String(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "indicator_key",
            "reference_period",
            name="uq_economic_event_occurrences_indicator_reference_period",
        ),
    )
    op.create_table(
        "economic_event_actual_value_vintages",
        sa.Column("indicator_key", sa.String(), nullable=False),
        sa.Column("reference_period", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revision_sequence", sa.Integer(), nullable=False),
        sa.Column("actual_value", sa.Numeric(), nullable=False),
        sa.Column("availability", sa.DateTime(timezone=True), nullable=True),
        sa.Column("availability_confidence", sa.String(), nullable=False),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("raw_source_value", sa.String(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(availability IS NULL) = (availability_confidence = 'UNKNOWN')",
            name="ck_economic_event_actual_value_vintages_avail_confidence",
        ),
        sa.ForeignKeyConstraint(
            ["indicator_key", "reference_period"],
            [
                "economic_event_occurrences.indicator_key",
                "economic_event_occurrences.reference_period",
            ],
            name="fk_economic_event_actual_value_vintages_occurrence",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "indicator_key",
            "reference_period",
            "revision_sequence",
            name="uq_economic_event_actual_value_vintages_identity",
        ),
    )
    op.create_index(
        "ix_economic_event_actual_value_vintages_occurrence_availability",
        "economic_event_actual_value_vintages",
        ["indicator_key", "reference_period", "availability"],
        unique=False,
    )
    op.create_table(
        "economic_event_consensus_vintages",
        sa.Column("indicator_key", sa.String(), nullable=False),
        sa.Column("reference_period", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revision_sequence", sa.Integer(), nullable=False),
        sa.Column("consensus_value", sa.Numeric(), nullable=False),
        sa.Column("availability", sa.DateTime(timezone=True), nullable=True),
        sa.Column("availability_confidence", sa.String(), nullable=False),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("raw_source_value", sa.String(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(availability IS NULL) = (availability_confidence = 'UNKNOWN')",
            name="ck_economic_event_consensus_vintages_avail_confidence",
        ),
        sa.ForeignKeyConstraint(
            ["indicator_key", "reference_period"],
            [
                "economic_event_occurrences.indicator_key",
                "economic_event_occurrences.reference_period",
            ],
            name="fk_economic_event_consensus_vintages_occurrence",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "indicator_key",
            "reference_period",
            "revision_sequence",
            name="uq_economic_event_consensus_vintages_identity",
        ),
    )
    op.create_index(
        "ix_economic_event_consensus_vintages_occurrence_availability",
        "economic_event_consensus_vintages",
        ["indicator_key", "reference_period", "availability"],
        unique=False,
    )
    op.create_table(
        "economic_event_schedule_vintages",
        sa.Column("indicator_key", sa.String(), nullable=False),
        sa.Column("reference_period", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revision_sequence", sa.Integer(), nullable=False),
        sa.Column("scheduled_date", sa.Date(), nullable=False),
        sa.Column("scheduled_time", sa.Time(), nullable=True),
        sa.Column("schedule_timezone", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("availability", sa.DateTime(timezone=True), nullable=True),
        sa.Column("availability_confidence", sa.String(), nullable=False),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(availability IS NULL) = (availability_confidence = 'UNKNOWN')",
            name="ck_economic_event_schedule_vintages_avail_confidence",
        ),
        sa.ForeignKeyConstraint(
            ["indicator_key", "reference_period"],
            [
                "economic_event_occurrences.indicator_key",
                "economic_event_occurrences.reference_period",
            ],
            name="fk_economic_event_schedule_vintages_occurrence",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "indicator_key",
            "reference_period",
            "revision_sequence",
            name="uq_economic_event_schedule_vintages_identity",
        ),
    )
    op.create_index(
        "ix_economic_event_schedule_vintages_occurrence_availability",
        "economic_event_schedule_vintages",
        ["indicator_key", "reference_period", "availability"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_economic_event_schedule_vintages_occurrence_availability",
        table_name="economic_event_schedule_vintages",
    )
    op.drop_table("economic_event_schedule_vintages")
    op.drop_index(
        "ix_economic_event_consensus_vintages_occurrence_availability",
        table_name="economic_event_consensus_vintages",
    )
    op.drop_table("economic_event_consensus_vintages")
    op.drop_index(
        "ix_economic_event_actual_value_vintages_occurrence_availability",
        table_name="economic_event_actual_value_vintages",
    )
    op.drop_table("economic_event_actual_value_vintages")
    op.drop_table("economic_event_occurrences")
    # ### end Alembic commands ###
