"""add economic event source mapping table

FX-52AH: persists the `(source, external_event_id, indicator_key) ->
occurrence_key` mapping FX-52A's original design derived via a pure
function instead -- see `domain.economic_calendar_occurrence_identity`'s
own module docstring and `application.ports.economic_event_source_
mapping_repository` for the full reasoning. A wholly new, independent
table with no relationship to any pre-existing schema shape.

FX-52AH.1 CORRECTION: the original version of this docstring claimed
downgrading this table was "ordinary, unguarded table removal" with
"no structural incompatibility between old and new schemas to protect
against" -- that reasoning considered only the SCHEMA shape, not the
DATA this table now holds once real ingestion has run against it.
Once mappings exist, this table is the ONLY place recording which
external `(source, external_event_id, indicator_key)` identities have
already been resolved to which `occurrence_key` -- dropping it while
non-empty would silently discard that resolution history, so a future
poll of an already-resolved external identity would re-run the
date-match correlation heuristic from scratch (and could, in the
zero/multiple-candidate cases, resolve differently, or not at all, the
second time). `downgrade()` now guards this exactly like migration
`76a4b23b2129`'s own `_raise_if_downgrade_would_lose_data` (FX-51H.1
precedent): refuses with a clear `RuntimeError` naming the row count
if `economic_event_source_mappings` is non-empty, before any
destructive DDL runs; proceeds normally when it is genuinely empty.

Revision ID: df99b7796566
Revises: 76a4b23b2129
Create Date: 2026-09-26 21:06:56.281592

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "df99b7796566"
down_revision: str | None = "76a4b23b2129"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_TABLE = "economic_event_source_mappings"


def _raise_if_downgrade_would_lose_data() -> None:
    """FX-52AH.1: refuses to drop `economic_event_source_mappings`
    while it holds any row -- see this migration's own module
    docstring for why a non-empty mapping table cannot be reversed
    without silently discarding resolved cross-source identity."""
    bind = op.get_bind()
    row_count: int = bind.execute(sa.text(f"SELECT COUNT(*) FROM {_TABLE}")).scalar_one()
    if row_count > 0:
        raise RuntimeError(
            f"Cannot downgrade migration df99b7796566: table {_TABLE!r} contains "
            f"{row_count} row(s). Dropping it would silently discard every already-"
            "resolved (source, external_event_id, indicator_key) -> occurrence_key "
            "mapping, including any correlation FX-52AH's own date-match heuristic "
            "already resolved once -- a future poll of that same external identity "
            "would have to re-run the heuristic from scratch and could resolve "
            "differently, or not at all, the second time. Downgrading past this "
            "migration once real mappings exist is a permanent limitation, not a bug "
            "-- restore from a backup instead."
        )


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "economic_event_source_mappings",
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("external_event_id", sa.String(), nullable=False),
        sa.Column("indicator_key", sa.String(), nullable=False),
        sa.Column("occurrence_key", sa.String(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "source",
            "external_event_id",
            "indicator_key",
            name="uq_economic_event_source_mappings_identity",
        ),
    )
    op.create_index(
        "ix_economic_event_source_mappings_occurrence_key",
        "economic_event_source_mappings",
        ["occurrence_key"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    _raise_if_downgrade_would_lose_data()

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_economic_event_source_mappings_occurrence_key",
        table_name="economic_event_source_mappings",
    )
    op.drop_table("economic_event_source_mappings")
    # ### end Alembic commands ###
