"""add economic event source mapping table

FX-52AH: persists the `(source, external_event_id, indicator_key) ->
occurrence_key` mapping FX-52A's original design derived via a pure
function instead -- see `domain.economic_calendar_occurrence_identity`'s
own module docstring and `application.ports.economic_event_source_
mapping_repository` for the full reasoning. A wholly new, independent
table with no relationship to any pre-existing schema shape -- unlike
migration `76a4b23b2129`, downgrading this one is ordinary, unguarded
table removal: there is no structural incompatibility between old and
new schemas to protect against, only the normal, expected data loss of
dropping a table, so no `_raise_if_downgrade_would_lose_data`-style
guard is warranted here.

Revision ID: df99b7796566
Revises: 76a4b23b2129
Create Date: 2026-09-26 21:06:56.281592

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "df99b7796566"
down_revision: str | None = "76a4b23b2129"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "economic_event_source_mappings",
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("external_event_id", sa.String(), nullable=False),
        sa.Column("indicator_key", sa.String(), nullable=False),
        sa.Column("occurrence_key", sa.String(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "source",
            "external_event_id",
            "indicator_key",
            name="uq_economic_event_source_mappings_identity",
        ),
    )
    op.create_index(
        "ix_economic_event_source_mappings_occurrence_key",
        "economic_event_source_mappings",
        ["occurrence_key"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_economic_event_source_mappings_occurrence_key",
        table_name="economic_event_source_mappings",
    )
    op.drop_table("economic_event_source_mappings")
    # ### end Alembic commands ###
